apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui-loadbalancer-service
  labels:
    app: streamlit-ui
spec:
  type: LoadBalancer
  selector:
    app: streamlit-ui
  ports:
    - port: 80
      targetPort: 8500
