apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui-deployment
  labels:
    app: streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      imagePullSecrets:
        - name: acr-auth  # Ensure this matches the secret name
      containers:
        - name: streamlit-ui
          image: IMAGE_PLACEHOLDER  # This will be replaced in the GitHub Action
          ports:
            - containerPort: 8500
