name: Deploy to AKS Cluster

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: acrforlawakscluster.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t acrforlawakscluster.azurecr.io/app1nginxaks:${{ github.run_id }} .
          docker push acrforlawakscluster.azurecr.io/app1nginxaks:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Set the target AKS cluster
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ secrets.AKS_NAME }}  
          resource-group: ${{ secrets.RESOURCE_GROUP }}  

      - name: Create Image Pull Secret
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_URL }}  
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: acr-auth  

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: manifests/deployment.yaml, manifests/service.yaml

          images: |
            acrforlawakscluster.azurecr.io/app1nginxaks:${{ github.run_id }}  
          imagepullsecrets: |
            acr-auth  
