name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: acrforlawakscluster.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t acrforlawakscluster.azurecr.io/app1nginx:${{ github.sha }} .
          docker push acrforlawakscluster.azurecr.io/app1nginx:${{ github.sha }}
